<br />
<br />


## 書籍

**杣取恵太**(2018).「第18章　本当に麻雀が強いのは誰か？
ディリクレ分布を用いた雀力のモデリング 」『たのしいベイズモデリング 
　　事例で拓く研究のフロンティア』豊田秀樹著，北大路出版, pp.191-198.[Amazon.co.jp](https://www.amazon.co.jp/%E3%81%9F%E3%81%AE%E3%81%97%E3%81%84%E3%83%99%E3%82%A4%E3%82%BA%E3%83%A2%E3%83%87%E3%83%AA%E3%83%B3%E3%82%B0-%E4%BA%8B%E4%BE%8B%E3%81%A7%E6%8B%93%E3%81%8F%E7%A0%94%E7%A9%B6%E3%81%AE%E3%83%95%E3%83%AD%E3%83%B3%E3%83%86%E3%82%A3%E3%82%A2-%E8%B1%8A%E7%94%B0-%E7%A7%80%E6%A8%B9/dp/4762830402)

**杣取恵太**(2017).「第9章　階層モデル」『ベイズ統計モデリング: R,JAGS, Stanによるチュートリアル 原著第2版』John K. Kruschke著，前田和寛・小杉考司監訳, 共立出版, pp.226-268.[Amazon.co.jp](https://www.amazon.co.jp/%E3%83%99%E3%82%A4%E3%82%BA%E7%B5%B1%E8%A8%88%E3%83%A2%E3%83%87%E3%83%AA%E3%83%B3%E3%82%B0-R-JAGS-Stan%E3%81%AB%E3%82%88%E3%82%8B%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB-%E5%8E%9F%E8%91%97%E7%AC%AC2%E7%89%88/dp/4320113160)

## 紀要・報告書

**杣取恵太**・坂本次郎・時田椋子・鈴木彩夏・国里愛彦 (2016) 診断精度研究の系統的レビューとメタアナリシス, 専修人間科学論集　心理学篇

## 国際会議発表

**Somatori, K.**, Kunisato, Y(2017). Do depressive symptoms influence randomness in decision making in the reversal learning task? – A hierarchical Bayesian modeling approach - The 50th Annual Meeting of the Society for Mathematical Psychology, July 23, Coventry, England.

**Somatori, K.**, Shimotomai, A., & Kunisato, Y. (2016). Does the Propositional Approach Co-exist Rescorla-Wagner model: the prediction of extinction form acquisition. The 46th annual Congress of the European Association for Behavioural and Cognitive Therapies, September 1, Stockholm, Sweden.

Sakamoto, J., **Somatori, K.**, & Kunisato, Y. (2016). Healthy university sutudents' day-to-day pain variability , depression, and pain-catastrophising: using the experience sampling method and Bayesian linear model. The 46th annual Congress of the European Association for Behavioural and Cognitive Therapies, September 1, Stockholm, Sweden.

**Somatori, K.**, Shimotomai, A., & Kunisato, Y. (2016). How people estimate their confidence: Bayesian model comparison leads to a more efficient model. The 31st International Congress of Psychology, July 27, Yokohama, Japan.

Sakamoto, J., **Somatori, K.**, & Kunisato, Y. (2016). Bayesian liner model for partial missing experience sampling method data: pain variability in healthy university students. The 31st International Congress of Psychology, July 29, Yokohama, Japan.

Sakamoto, J., **Somatori, K.**, Okubo, M., & Kunisato, Y. (2015). Depression and Intertemporal Choice of Pain: Maximum Likelihood Estimation vs. Hierarchical Bayesian Analysis. The 48th Annual Meeting of the Society for Mathematical Psychology, July 18, Newport Beach, California, USA.

**Somatori, K.**, Sakamoto, J., Shimotomai, A., & Kunisato, Y(2015). What is a true measure for meta-cognition?: A Bayesian cognitive modeling approach. The 48th Annual Meeting of the Society for Mathematical Psychology, July 18, Newport Beach, California, USA.

## 国内学会発表

### ポスター発表

**杣取恵太**・国里愛彦 (2017). 恐怖条件づけにおける実験パラメータの検討:
恐怖顔および叫び声を無条件刺激とした恐怖条件づけに必要な実験環境について
　日本認知・行動療法学会第43回大会 新潟 2017年9月30日

**杣取恵太**・下斗米淳・国里愛彦 (2016). 命題アプローチにおける恐怖条件づけの学習過程―Rescorla-Wargner モデルを用いた推定―　日本認知・行動療法学会第42回大会 徳島 2016年10月9日

坂本次郎・**杣取恵太**・国里愛彦 (2016). 日常場面における痛みと痛みの変動性が抑うつおよび破局的試行に与える影響ーー集中縦断データと線形ベイズモデルを用いた検討ーー　日本認知・行動療法学会第42回大会 徳島 2016年10月9日

**杣取恵太**・下斗米淳・国里愛彦 2015 新たなメタ認知課題の作成と妥当性の検討 日本認知・行動療法学会第41回大会　仙台 2015年10月2日

時田椋子・坂本次郎・**杣取恵太**・澤幸祐・国里愛彦　2015 経験サンプリングにおける喫煙に渇望が与える影響：系統的レビューとメタアナリシス　日本認知・行動療法学会第41回大会　仙台 2015年10月3日

**杣取恵太**・国里愛彦・村松　励 (2014). 自己愛パーソナリティの誇大特性と過敏特性が非行に与える影響－共感性との関連－　日本認知・行動療法学会第40回大会　富山　2014年11月2日

### 口頭発表・シンポジウム等

**杣取恵太** (2018) 係留ビネット法を用いた反応バイアスの補正
自主企画シンポジウム「項目反応モデルを用いた心理学実践研究と応用可能性」 話題提供 日本心理学会大82回大会 宮城 2018年9月28日

**杣取恵太** (2017) ベイズ統計学の基本: 
ベイジアン統計モデリングの有効性と実践
自主企画シンポジウム「臨床実践と研究に活かすベイズ統計学」 企画・司会・話題提供 日本認知・行動療法学会第43回大会 新潟 2017年9月30日

**杣取恵太** (2017) ベイズ統計モデリングを用いたメタ認知の推定
自主企画シンポジウム「心理学におけるベイズ統計モデリングの可能性」話題提供 日本心理学会第81回大会 福岡 2017年9月22日

**杣取恵太** (2016) 命題アプローチ:連合学習の認知的側面　
自主企画シンポジウム「連合学習理論の発展と臨床との接点」話題提供 日本認知・行動療法学会第42回大会 徳島 2016年10月10日

国里愛彦・**杣取恵太** (2015)　連合学習理論と不安症　シンポジウム「不安障害の心理学基礎研究と認知行動療法」　第7回日本不安症学会学術大会　広島　2015年2月15日 *抄録集では杣取恵太の名前が抜けていますが共同発表を行いました。


<br />
<p>Copyright &copy; 2017 Keita Somatori. All rights reserved </p>